version: "3"

services:
  backend: &backend
      hostname: django
      restart: always
      build:
        context: ..
        dockerfile: ./storaging/docker-build/Dockerfile
        args:
          - REQUIREMENTS_PATH=/app/requirements.txt
      command: bash ./docker-build/start
      volumes:
        - .:/app
        - static_volume:/app/django_static
        - media_volume:/app/django_media
      ports:
        - 8000:8000
      depends_on:
        - postgres
        - celery-beat
      networks:
        - net
      env_file:
        - environment
  postgres:
      env_file:
        - environment
      image: postgres:13.1
      restart: always
      ports:
        - "5439:5432"
      volumes:
        - db_data:/home/postgresql
        - db_data:/var/log/postgresql
      networks:
        - net
  redis:
      image: redis:7.0.0
      restart: always
      container_name: redis
      command: [ "redis-server", "--port", "6379", "--appendonly", "yes","--maxmemory", "1gb", "--maxmemory-policy", "allkeys-lru" ]
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      networks:
        - net

  celery-worker:
      <<: *backend
      restart: always
      container_name: celery-worker
      entrypoint: celery
      command: -A settings worker --loglevel=info
      depends_on:
        - redis
        - postgres
      networks:
        - net

  celery-beat:
      <<: *backend
      container_name: celery-beat
      restart: always
      command: -A settings beat --loglevel=info
      depends_on:
        - celery-worker
        - redis
      networks:
        - net
      ports: []

networks:
  net:

volumes:
    static_volume: { }
    media_volume: { }
    db_data:
        external: true
    redis_data:
      external: true
