version: "3"

services:
  backend:
      hostname: django
      restart: always
      build:
        context: ..
        dockerfile: ./storaging/docker-build/Dockerfile
        args:
          - REQUIREMENTS_PATH=/app/requirements.txt
      command: bash ./docker-build/start
      volumes:
        - .:/app
        - static_volume:/app/django_static
        - media_volume:/app/django_media
      ports:
        - 8000:8000
      depends_on:
        - postgres
        - celery-beat
      networks:
        - net
      env_file:
        - environment
  postgres:
      env_file:
        - environment
      image: postgres:13.1
      restart: always
      ports:
        - "5439:5432"
      volumes:
        - db_data:/home/postgresql
        - db_data:/var/log/postgresql
      networks:
        - net
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  celery-beat:
    build:
        context: ..
        dockerfile: ./storaging/docker-build/Dockerfile
    volumes:
      - ./project/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - rabbitmq
#    command: bash ./docker-build/start celery


networks:
  net:

volumes:
    static_volume: { }
    media_volume: { }
    db_data:
        external: true
