# Generated by Django 4.2.7 on 2024-02-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Автор"
                    ),
                ),
                (
                    "quote",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Цитата",
                "verbose_name_plural": "Цитаты",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Наименование склада"
                    ),
                ),
                ("address", models.CharField(max_length=150, verbose_name="Адрес")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Описание"
                    ),
                ),
                ("useful_value", models.FloatField(verbose_name="Площадь")),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
            },
        ),
        migrations.CreateModel(
            name="StorageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="Наименование типа хранения",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Описание"
                    ),
                ),
                ("storage_value", models.FloatField(verbose_name="Вместимость")),
                (
                    "warehouse",
                    models.ManyToManyField(
                        to="warehouses.warehouse", verbose_name="Склад"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип хранения",
                "verbose_name_plural": "Типы хранения",
            },
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Наименование груза"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Описание"
                    ),
                ),
                ("cargo_value", models.FloatField(verbose_name="Объем груза")),
                ("cargo_weight", models.FloatField(verbose_name="Вес груза")),
                (
                    "storage_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouses.storagetype",
                        verbose_name="Тип хранения",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouses.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Груз",
                "verbose_name_plural": "Грузы",
            },
        ),
    ]
