# Generated by Django 4.2.7 on 2024-02-19 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="storage_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouses.storagetype",
                verbose_name="Тип хранения",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouses.warehouse",
                verbose_name="Склад",
            ),
        ),
    ]
