#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate --noinput
python /app/manage.py collectstatic --noinput
python /app/manage.py runserver 0.0.0.0:8000

if [[ $1 == "celery" ]]; then
  celery -A settings.celery worker --loglevel=DEBUG
elif [[ $1 == "celery_beat" ]]; then
  rm -rf celerybeat.pid
  celery -A settings.celery purge -f -Q beat
  celery -A settings.celery beat --loglevel=DEBUG
fi