#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


if [[ $1 == "server" ]]; then
  python /app/manage.py migrate --noinput
  python /app/manage.py collectstatic --noinput
  python /app/manage.py runserver 0.0.0.0:8000
elif [[ $1 == "celery-worker" ]]; then
  celery -A celery worker --loglevel=DEBUG
elif [[ $1 == "celery_beat" ]]; then
  rm -rf celerybeat.pid
  celery -A celery purge -f -Q beat
  celery -A celery beat --loglevel=DEBUG
fi